### ISSUE TITLE
Installation failure associated to `klaw-sync`

### ISSUE THREAD

**Issue by lachrist** [applandinc/appmap-agent-js#113]
[@Laurent Christophe](https://applanding.slack.com/team/U01R92Z9X52)
 there's one from Sept 5 that mentions klaw-sync, can you take a look at it? The link to the full telemetry output is in the sheet in column G. Thanks!

**Comment by lachrist** [comment]
```
Running command: `node --version`

v18.8.0


Running command: `npm install --saveDev @appland/appmap-agent-js@latest`

npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@appland/appmap-agent-js@11.2.0',
npm WARN EBADENGINE   required: { node: '14.x.x || 16.x.x || 17.x.x' },
npm WARN EBADENGINE   current: { node: 'v18.8.0', npm: '8.18.0' }
npm WARN EBADENGINE }
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

added 1211 packages, and audited 1212 packages in 39s

39 packages are looking for funding
  run `npm fund` for details

53 vulnerabilities (17 moderate, 33 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.


Running command: `npx appmap-agent-js init /Users/<USER>/Sites/<PROJECT>/backend`

node:fs:1596
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat '/Users/<USER>/Sites/<PROJECT>/backend/public/storage'
    at Object.statSync (node:fs:1596:3)
    at klawSync (/Users/<USER>/Sites/<PROJECT>/backend/node_modules/klaw-sync/klaw-sync.js:16:24)
    at file:///Users/<USER>/Sites/<PROJECT>/backend/node_modules/@appland/appmap-agent-js/components/init/node/index.mjs:78:9
    at Array.forEach (<anonymous>)
    at findDirsWithFiles (file:///Users/<USER>/Sites/<PROJECT>/backend/node_modules/@appland/appmap-agent-js/components/init/node/index.mjs:60:10)
    at run (file:///Users/<USER>/Sites/<PROJECT>/backend/node_modules/@appland/appmap-agent-js/components/init/node/index.mjs:86:25)
    at main (file:///Users/<USER>/Sites/<PROJECT>/backend/node_modules/@appland/appmap-agent-js/components/init/node/index.mjs:110:20)
    at file:///Users/<USER>/Sites/<PROJECT>/backend/node_modules/@appland/appmap-agent-js/lib/node/init.mjs:7:16
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/<USER>/Sites/<PROJECT>/backend/public/storage'
}

Node.js v18.8.0
```

**Comment by lachrist** [comment]
@alan the user wrote:

```
npx appmap-agent-js init /Users/<USER>/Sites/<PROJECT>/backend
```

So if I'm not mistaking, he invoked to command himself and provided a custom directory. Would that explain why `klaw-sync` throws an exception? If this is the case, is it something that we should address or is the fault of the user?

**Comment by apotterri** [comment]
The `init` subcommand is using `klawSync` to walk the project tree, looking for packages to add to `appmap.yml`. For whatever reason, `readdirSync` seems to be returning an entry that `statSync` can't read.

I'd say it would be appropriate to pass `false` for the `throwIfNoEntry` arg to [`statSync`](https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#fsstatsyncpath-options), and update [`hasMatch`](https://github.com/applandinc/appmap-agent-js/blob/main/components/init/node/index.mjs#L31) so it's prepared for `item.stats` to be `undefined`.

**Comment by lachrist** [comment]
It think I got it. I will add a fix in the current pull request if that is okay with you.

**Comment by lachrist** [comment]
@apotterri Actually the place where the exception is thrown is in [klaw-sync](https://github.com/manidlou/node-klaw-sync/blob/222775b25c4734f47a5cdf107ce5c02fb50066e0/klaw-sync.js#L16). So we cannot pass the lenient option. The only thing we can do is to wrap the `klaw` call inside a `try ... catch` block. But I'm not sure I want to do that. The only way I can explain this failure is that the file system was modified between a `readdirSync` and the faulty `statSync`. If this is indeed the case, I don't think we should consider such scenario.

**Comment by apotterri** [comment]
Oh, oops, sorry for the misdirect for the user's error. I do think we should make the change, I suggested, though.

So, unfortunately, I've seen a bunch of cases on macOS where `readdirSync` returns out-of-date directory entries, that subsequent `stat` calls can't see. It's really annoying, and is almost certainly going to continue to happen.

> Edit: Never mind, I saw that you can provide fs as parameter!
Ah, good, I was just going to mention this.

**Comment by lachrist** [comment]
What do you think of https://github.com/applandinc/appmap-agent-js/pull/117/commits/7b3a7bf6c9e0335ca230d62548193cca540cfc96 ?

**Comment by apotterri** [comment]
Looks good to me.
