### ISSUE TITLE
ESM Module loader for main file instead of CJS

### ISSUE THREAD

**Issue by lachrist** [applandinc/appmap-agent-js#118]
To instrument esm modules we use the node's `--experimental-loader` cli argument. Unfortunately this causes node to use the esm module loader for the main file instead of the cjs. And these two loaders do not behave exactly the same way. Here is an example of crash due to this discrepancy:

```txt
PS D:\subversion01\MobileApps\netFIELD\dev\iolink-engineering-tool\trunk> cd service
PS D:\subversion01\MobileApps\netFIELD\dev\iolink-engineering-tool\trunk\service> npx appmap-agent-js -- npm run debug
(node:17808) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17808) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: transformSource
(node:24548) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24548) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: transformSource
> netfield-app-io-link-configurator@1.0.0 debug
> nodemon --config nodemon.json --inspect=2935 src/index.ts
(node:1724) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1724) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: transformSource
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: js,json,ts
[nodemon] starting `node -r ts-node/register --inspect=2935 src/index.ts`
Debugger listening on ws://127.0.0.1:2935/667fb4f1-3ef0-4e58-a0ff-26979a98f345
For help, see: https://nodejs.org/en/docs/inspector
(node:3764) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Unknown file extension ".ts" for D:\subversion01\MobileApps\netFIELD\dev\iolink-engineering-tool\trunk\service\src\index.ts
    at new NodeError (node:internal/errors:387:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:165:28)
    at Object.hook.load (file:///D:/subversion01/MobileApps/netFIELD/dev/iolink-engineering-tool/trunk/service/node_modules/@appland/appmap-agent-js/components/hook-esm/node/index.mjs:44:40)
    at load (file:///D:/subversion01/MobileApps/netFIELD/dev/iolink-engineering-tool/trunk/service/node_modules/@appland/appmap-agent-js/lib/node/__common__.mjs:38:28)
    at nextLoad (node:internal/modules/esm/loader:165:28)
    at ESMLoader.load (node:internal/modules/esm/loader:608:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:464:22)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by lachrist** [comment]
Related change: https://github.com/getappmap/appmap-agent-js/pull/123

**Comment by lachrist** [comment]
npx appmap-agent-js --recorder=mocha -- npx mocha
===
{}
===
(node:10636) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
,(node:4744) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
,internal/process/esm_loader.js:74
internalBinding('errors').triggerUncaughtException(
^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for C:\Users\REDACTED\REDACTED\website\node_modules\mocha\bin\mocha
at new NodeError (internal/errors.js:322:7)
at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
at Loader.getFormat (internal/modules/esm/loader.js:105:42)
at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
at async Loader.import (internal/modules/esm/loader.js:177:17)
at async Object.loadESM (internal/process/esm_loader.js:68:5)
at async handleMainPromise (internal/modules/run_main.js:59:12) {
code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
