### ISSUE TITLE
Bug: Test errors when run with appmap agent

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#37]
App: https://github.com/sasha7/notes-app

Console output: _(also note the typo "hoop")_
```
npx appmap-agent-js
APPMAP-WARNING command "git describe --abbrev=0 --tags" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --abbrev=0" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long --tags" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-INFO Trace port: 56476
APPMAP-INFO mocha ...
[AppmapAgent] Symbolic link "/Users/ptrdvrk/work/github/js/notes-app/node_modules/.bin/mocha" refers to "../mocha/bin/mocha" which has no extension, this is problematic for the node's esm loader which is enabled by --experimental-loader. To solve this issue, the agent is going to create copy of that file with a '.cjs' extension and overwrite the link to refer to that file. We hoop this is okay with you...
(node:60206) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60207) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/ptrdvrk/work/github/js/notes-app/node_modules/mocha/bin/_mocha
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
APPMAP-INFO > Exited with: 1
# ptrdvrk • ~/work/github/js/notes-app • master*
‣ npx appmap-agent-js
APPMAP-WARNING command "git describe --abbrev=0 --tags" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --abbrev=0" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long --tags" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-INFO Trace port: 56478
APPMAP-INFO mocha ...
(node:60253) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60254) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/ptrdvrk/work/github/js/notes-app/node_modules/mocha/bin/_mocha
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
APPMAP-INFO > Exited with: 1

```

**Comment by ptrdvrk** [comment]
I am seeing the same issue in https://github.com/dye784/Chat-App

```
npx appmap-agent-js
APPMAP-WARNING command "git describe --abbrev=0 --tags" on cwd "/Users/ptrdvrk/work/github/js/Chat-App" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --abbrev=0" on cwd "/Users/ptrdvrk/work/github/js/Chat-App" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long --tags" on cwd "/Users/ptrdvrk/work/github/js/Chat-App" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long" on cwd "/Users/ptrdvrk/work/github/js/Chat-App" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-INFO Trace port: 50063
APPMAP-INFO mocha --compilers js:babel-register --watch-extensions js,jsx tests/**/**/*.test.js tests/**/**/*.test.jsx ...
APPMAP-WARNING The mocha recorder cannot recursively record processes.
[AppmapAgent] Symbolic link "/Users/ptrdvrk/work/github/js/Chat-App/node_modules/.bin/mocha" refers to "../mocha/bin/mocha" which has no extension, this is problematic for the node's esm loader which is enabled by --experimental-loader. To solve this issue, the agent is going to create copy of that file with a '.cjs' extension and overwrite the link to refer to that file. We hoop this is okay with you...
(node:24320) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24321) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/ptrdvrk/work/github/js/Chat-App/node_modules/mocha/bin/_mocha
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
APPMAP-INFO > Exited with: 1
```

**Comment by lachrist** [comment]
This is because of non supported mocha version. Meaningful error message in https://github.com/applandinc/appmap-agent-js/commit/3bfb515564c28e39b5671c0333e4849f7e60f101. Could you check that the presence of the meaningful error message in `@appland/appmap-agent-js@6.3.0`?

**Comment by kgilpin** [comment]
Have we started the agent helper commands for the JS agent yet?

We can be sure and capture these types of version constraints.

**Comment by lachrist** [comment]
There is such an helper in the agent already. I capture system-level constraints there. The few constraints on npm package modules version that are implemented on need basis. I think these two checks are complementary. Checks at setup time are more user friendly, checks at runtime are still important because they deal with the actual material in use.

**Comment by lachrist** [comment]
We could make a feature request to implement all check at setup time as well. But for now I would like to focus on bugs.

**Comment by ptrdvrk** [comment]
Re-tested with v6.4.0 & mocha 8.0.0. I am getting the following error:

```
npx appmap-agent-js --recorder=mocha --command="mocha"
APPMAP-WARNING command "git describe --abbrev=0 --tags" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --abbrev=0" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long --tags" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-WARNING command "git describe --long" on cwd "/Users/ptrdvrk/work/github/js/notes-app" failed with 128 >> fatal: No names found, cannot describe anything.

APPMAP-INFO Trace port: 53651
APPMAP-INFO mocha ...
APPMAP-WARNING The mocha recorder cannot recursively record processes.
(node:91024) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
APPMAP-INFO Please, ignore node's deprecated warning about outdated transformSource loader hook (if present).
APPMAP-INFO Please, ignore node's deprecated warning about outdated transformSource loader hook (if present).
APPMAP-INFO Recorder 'mocha' caught process 91024
APPMAP-INFO Recording /Users/ptrdvrk/work/github/js/notes-app/node_modules/.bin/mocha.
Only utf-8 encoding is currently supported, got: "application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm9iamVjdGlvbi5qcyJdLCJuYW1lcyI6WyJNb2RlbEJhc2UiLCJNb2RlbCIsIlF1ZXJ5QnVpbGRlciIsIlF1ZXJ5QnVpbGRlckJhc2UiLCJRdWVyeUJ1aWxkZXJPcGVyYXRpb24iLCJSZWxhdGlvbkV4cHJlc3Npb24iLCJWYWxpZGF0aW9uRXJyb3IiLCJSZWxhdGlvbiIsIkhhc09uZVJlbGF0aW9uIiwiSGFzTWFueVJlbGF0aW9uIiwiQmVsb25nc1RvT25lUmVsYXRpb24iLCJNYW55VG9NYW55UmVsYXRpb24iLCJ0cmFuc2FjdGlvbiIsIlByb21pc2UiLCJPYmplY3QiLCJkZWZpbmVQcm9wZXJ0eSIsIm1vZHVsZSIsImV4cG9ydHMiLCJnZXQiLCJjb25zb2xlIiwid2FybiJdLCJtYXBwaW5ncyI6Ijs7Ozs7OztBQUFBOzs7O0FBQ0E7Ozs7QUFDQTs7OztBQUNBOzs7O0FBQ0E7Ozs7QUFDQTs7OztBQUNBOzs7O0FBRUE7Ozs7QUFDQTs7OztBQUNBOzs7O0FBQ0E7Ozs7QUFDQTs7OztBQUVBOzs7O0FBQ0E7Ozs7OztRQUdFQSxTO1FBQ0FDLEs7UUFDQUMsWTtRQUNBQyxnQjtRQUNBQyxxQjtRQUNBQyxrQjtRQUNBQyxlO1FBQ0FDLFE7UUFDQUMsYztRQUNBQyxlO1FBQ0FDLG9CO1FBQ0FDLGtCO1FBQ0FDLFc7UUFDQUMsTzs7O0FBR0ZDLE9BQU9DLGNBQVAsQ0FBc0JDLE9BQU9DLE9BQTdCLEVBQXNDLGtCQUF0QyxFQUEwRDtBQUN4REMsT0FBSyxlQUFZO0FBQ2ZDLFlBQVFDLElBQVI7QUFDQTtBQUNEO0FBSnVELENBQTFEOztBQU9BTixPQUFPQyxjQUFQLENBQXNCQyxPQUFPQyxPQUE3QixFQUFzQyxtQkFBdEMsRUFBMkQ7QUFDekRDLE9BQUssZUFBWTtBQUNmQyxZQUFRQyxJQUFSO0FBQ0E7QUFDRDtBQUp3RCxDQUEzRCIsImZpbGUiOiJvYmplY3Rpb24uanMiLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgTW9kZWxCYXNlIGZyb20gJy4vbW9kZWwvTW9kZWxCYXNlJztcbmltcG9ydCBNb2RlbCBmcm9tICcuL21vZGVsL01vZGVsJztcbmltcG9ydCBRdWVyeUJ1aWxkZXJCYXNlIGZyb20gJy4vcXVlcnlCdWlsZGVyL1F1ZXJ5QnVpbGRlckJhc2UnO1xuaW1wb3J0IFF1ZXJ5QnVpbGRlciBmcm9tICcuL3F1ZXJ5QnVpbGRlci9RdWVyeUJ1aWxkZXInO1xuaW1wb3J0IFF1ZXJ5QnVpbGRlck9wZXJhdGlvbiBmcm9tICcuL3F1ZXJ5QnVpbGRlci9vcGVyYXRpb25zL1F1ZXJ5QnVpbGRlck9wZXJhdGlvbidcbmltcG9ydCBSZWxhdGlvbkV4cHJlc3Npb24gZnJvbSAnLi9xdWVyeUJ1aWxkZXIvUmVsYXRpb25FeHByZXNzaW9uJztcbmltcG9ydCBWYWxpZGF0aW9uRXJyb3IgZnJvbSAnLi9WYWxpZGF0aW9uRXJyb3InO1xuXG5pbXBvcnQgUmVsYXRpb24gZnJvbSAnLi9yZWxhdGlvbnMvUmVsYXRpb24nO1xuaW1wb3J0IEhhc09uZVJlbGF0aW9uIGZyb20gJy4vcmVsYXRpb25zL2hhc09uZS9IYXNPbmVSZWxhdGlvbic7XG5pbXBvcnQgSGFzTWFueVJlbGF0aW9uIGZyb20gJy4vcmVsYXRpb25zL2hhc01hbnkvSGFzTWFueVJlbGF0aW9uJztcbmltcG9ydCBCZWxvbmdzVG9PbmVSZWxhdGlvbiBmcm9tICcuL3JlbGF0aW9ucy9iZWxvbmdzVG9PbmUvQmVsb25nc1RvT25lUmVsYXRpb24nO1xuaW1wb3J0IE1hbnlUb01hbnlSZWxhdGlvbiBmcm9tICcuL3JlbGF0aW9ucy9tYW55VG9NYW55L01hbnlUb01hbnlSZWxhdGlvbic7XG5cbmltcG9ydCB0cmFuc2FjdGlvbiBmcm9tICcuL3RyYW5zYWN0aW9uJztcbmltcG9ydCBQcm9taXNlIGZyb20gJ2JsdWViaXJkJztcblxuZXhwb3J0IHtcbiAgTW9kZWxCYXNlLFxuICBNb2RlbCxcbiAgUXVlcnlCdWlsZGVyLFxuICBRdWVyeUJ1aWxkZXJCYXNlLFxuICBRdWVyeUJ1aWxkZXJPcGVyYXRpb24sXG4gIFJlbGF0aW9uRXhwcmVzc2lvbixcbiAgVmFsaWRhdGlvbkVycm9yLFxuICBSZWxhdGlvbixcbiAgSGFzT25lUmVsYXRpb24sXG4gIEhhc01hbnlSZWxhdGlvbixcbiAgQmVsb25nc1RvT25lUmVsYXRpb24sXG4gIE1hbnlUb01hbnlSZWxhdGlvbixcbiAgdHJhbnNhY3Rpb24sXG4gIFByb21pc2Vcbn07XG5cbk9iamVjdC5kZWZpbmVQcm9wZXJ0eShtb2R1bGUuZXhwb3J0cywgXCJPbmVUb09uZVJlbGF0aW9uXCIsIHtcbiAgZ2V0OiBmdW5jdGlvbiAoKSB7XG4gICAgY29uc29sZS53YXJuKGBPbmVUb09uZVJlbGF0aW9uIGlzIGRlcHJlY2F0ZWQgYW5kIHdpbGwgYmUgcmVtb3ZlZCBpbiB2ZXJzaW9uIDAuNy4wLiBVc2UgQmVsb25nc1RvT25lUmVsYXRpb24gaW5zdGVhZC4gU2ltcGx5IHJlcGxhY2UgT25lVG9PbmVSZWxhdGlvbiB3aXRoIEJlbG9uZ3NUb09uZVJlbGF0aW9uLmApO1xuICAgIHJldHVybiBCZWxvbmdzVG9PbmVSZWxhdGlvbjtcbiAgfVxufSk7XG5cbk9iamVjdC5kZWZpbmVQcm9wZXJ0eShtb2R1bGUuZXhwb3J0cywgXCJPbmVUb01hbnlSZWxhdGlvblwiLCB7XG4gIGdldDogZnVuY3Rpb24gKCkge1xuICAgIGNvbnNvbGUud2FybihgT25lVG9NYW55UmVsYXRpb24gaXMgZGVwcmVjYXRlZCBhbmQgd2lsbCBiZSByZW1vdmVkIGluIHZlcnNpb24gMC43LjAuIFVzZSBIYXNNYW55UmVsYXRpb24gaW5zdGVhZC4gU2ltcGx5IHJlcGxhY2UgT25lVG9NYW55UmVsYXRpb24gd2l0aCBIYXNNYW55UmVsYXRpb24uYCk7XG4gICAgcmV0dXJuIEhhc01hbnlSZWxhdGlvbjtcbiAgfVxufSk7XG5cbiJdfQ==".
APPMAP-INFO > Exited with: 1

```

**Comment by lachrist** [comment]
This should have been fixed in: https://github.com/applandinc/appmap-agent-js/commit/fb579274d46a748dfa4cdc35bc162d63d5f3e2f2

**Comment by ptrdvrk** [comment]
Mocha isn't behaving well in this app after upgrade to v8.0.0 so I am closing this.
