### ISSUE TITLE
Handle spaces in installation path

### ISSUE THREAD

**Issue by lachrist** [applandinc/appmap-agent-js#88]
```
:x: Somebody failed to install. Here are the details:
name:
@appland/appmap/install-agent:failure
common.platformversion:
21.2.0
common.os:
darwin
appmap.cli.sessionId:
54ea02ffb5bbaf7e2e59a0fc38e7b90bf1d62ad44cdaecee6d4ed7236e09598b
appmap.cli.machineId:
fe4f6dcfba35b9fcf94766e3c01fe676c0003244e3a338150e108da0c6218def
appmap.cli.version:
3.15.1
appmap.cli.args:
/Users/alexhaddad/.npm/_npx/3007b677135bbf3c/node_modules/.bin/appmap install /Users/alexhaddad/My Drive/UCLA/Clubs/DevX Sike/SikeApp
common.source:
@appland/appmap
appmap.cli.exception_type:
ChildProcessError
common.arch:
arm64
appmap.cli.exception:
y%20Drive/UCLA/Clubs/DevX%20Sike/SikeApp/node_modules/@appland/appmap-agent-js/components/status/node/index.mjs:81:20)
[31m>  [39m    at file:///Users/alexhaddad/My%20Drive/UCLA/Clubs/DevX%20Sike/SikeApp/node_modules/@appland/appmap-agent-js/lib/node/status.mjs:7:16
[31m>  [39m    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
[31m>  [39m    at async Promise.all (index 0)
[31m>  [39m    at async ESMLoader.import (node:internal/modules/esm/loader:281:24) {
[31m>  [39m  errno: -2,
[31m>  [39m  code: 'ENOENT',
[31m>  [39m  syscall: 'chdir',
[31m>  [39m  path: '/Users/alexhaddad/My Drive/UCLA/Clubs/DevX Sike/SikeApp',
[31m>  [39m  dest: '/Users/alexhaddad/My'
[31m>  [39m}
   at ChildProcess.<anonymous> (/Users/alexhaddad/.npm/_npx/3007b677135bbf3c/node_modules/@appland/appmap/built/src/cmds/agentInstaller/commandRunner.js:100:27)
   at ChildProcess.emit (node:events:390:28)
   at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
appmap.cli.log:
l/bootstrap/switches/does_own_process_state:112:14)
   at Object.lsPackage (file:///Users/alexhaddad/My%20Drive/UCLA/Clubs/DevX%20Sike/SikeApp/node_modules/@appland/appmap-agent-js/components/status/node/index.mjs:11:13)
   at run (file:///Users/alexhaddad/My%20Drive/UCLA/Clubs/DevX%20Sike/SikeApp/node_modules/@appland/appmap-agent-js/components/status/node/index.mjs:53:34)
   at main (file:///Users/alexhaddad/My%20Drive/UCLA/Clubs/DevX%20Sike/SikeApp/node_modules/@appland/appmap-agent-js/components/status/node/index.mjs:81:20)
   at file:///Users/alexhaddad/My%20Drive/UCLA/Clubs/DevX%20Sike/SikeApp/node_modules/@appland/appmap-agent-js/lib/node/status.mjs:7:16
   at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
   at async Promise.all (index 0)
   at async ESMLoader.import (node:internal/modules/esm/loader:281:24) {
 errno: -2,
 code: 'ENOENT',
 syscall: 'chdir',
 path: '/Users/alexhaddad/My Drive/UCLA/Clubs/DevX Sike/SikeApp',
 dest: '/Users/alexhaddad/My'
}
appmap.cli.installers_available:
npm, yarn
appmap.cli.directory:
.DS_Store
.env
.expo
.expo-shared
.git
.gitignore
.nvmrc
.watchmanconfig
App.js
README.md
app.config.js
appmap.yml
assets
babel.config.js
components
config
hooks
navigation
node_modules
package-lock.json
package.json
providers
screens
utils
yarn.lock
appmap.cli.path:
/Users/alexhaddad/My Drive/UCLA/Clubs/DevX Sike/SikeApp
appmap.cli.installer:
npm
appmap.cli.duration:
15.355
timestamp:
2022-01-22T21:22:54.575Z
```

**Comment by lachrist** [comment]
@apotterri can we mark this issue as fixed?

**Comment by lachrist** [comment]
@apotterri I still see https://applanding.slack.com/archives/C02DU9210Q2/p1643342652021629 which is after the merge.

**Comment by apotterri** [comment]
As we discussed in Slack, the failure you linked to isn't related the space in the path.

I believe this issue can be closed, yes.
